### ISSUE TITLE
some minor changed (client ask)

### ISSUE THREAD

**Issue by trikaryateknologi** [trikaryateknologi/hisamitsuv2#1]
![unnamed](https://cloud.githubusercontent.com/assets/17698346/24852715/b4d88a84-1e02-11e7-9be7-2e25ef664438.jpg)
![unnamed2](https://cloud.githubusercontent.com/assets/17698346/24852713/b4c45172-1e02-11e7-9f0e-2fb588a741da.jpg)
![unnamed3](https://cloud.githubusercontent.com/assets/17698346/24852714/b4c8298c-1e02-11e7-9d7a-249c22686cc7.jpg)
![unnamed4](https://cloud.githubusercontent.com/assets/17698346/24852716/b503346e-1e02-11e7-870b-0ad9faaee115.jpg)

**Comment by lapantiga** [comment]
iki wis beress...case closed
